-- Stage 6A: persist per-company alias research attempts.
-- Run manually in the Supabase SQL editor before using the batch orchestrator.

begin;

create table if not exists public.company_alias_enrichment_runs (
    run_id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(company_id)
        on delete cascade,
    status text not null,
    model text not null,
    attempt_count integer not null default 1,
    company_verified boolean,
    suggestions_received integer not null default 0,
    aliases_saved integer not null default 0,
    error_message text,
    started_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,
    constraint company_alias_enrichment_runs_status_check
        check (status in ('RUNNING', 'SUCCESS', 'FAILED')),
    constraint company_alias_enrichment_runs_attempt_count_check
        check (attempt_count >= 1),
    constraint company_alias_enrichment_runs_counts_check
        check (suggestions_received >= 0 and aliases_saved >= 0)
);

create index if not exists company_alias_enrichment_runs_company_idx
    on public.company_alias_enrichment_runs (company_id, started_at desc);

create index if not exists company_alias_enrichment_runs_success_idx
    on public.company_alias_enrichment_runs (company_id)
    where status = 'SUCCESS';

comment on table public.company_alias_enrichment_runs is
    'Audit log and repeat-prevention state for AI company alias research.';

commit;
