-- Article Analyzer Stage 1: versioned, per-article structured analysis.
--
-- This table intentionally stores analysis of one article. Canonical events and
-- article-to-event clustering will be introduced separately, because multiple
-- articles can describe the same underlying event.

begin;

create table if not exists public.article_analyses (
    analysis_id bigint generated by default as identity primary key,
    article_id bigint not null references public.articles(article_id)
        on delete cascade,
    relevance_id bigint not null references public.article_relevance(relevance_id)
        on delete cascade,

    status text not null default 'RUNNING',
    has_event boolean,
    event_type text,
    impact_direction text,
    impact_strength smallint,
    importance_score smallint,
    confidence numeric(4, 3),
    time_horizon text,
    event_date date,

    summary text,
    industry_implication text,
    facts text[] not null default '{}'::text[],
    risk_factors text[] not null default '{}'::text[],

    input_type text not null default 'RSS_SUMMARY',
    model text not null,
    prompt_version text not null,
    analysis_version text not null,
    error_message text,
    started_at timestamp with time zone not null default now(),
    analyzed_at timestamp with time zone,

    constraint article_analyses_status_check
        check (status in ('RUNNING', 'SUCCESS', 'FAILED')),
    constraint article_analyses_event_type_check
        check (
            event_type is null
            or event_type in (
                'GOVERNMENT_CONTRACT',
                'COMMERCIAL_CONTRACT',
                'PRODUCT_LAUNCH',
                'SATELLITE_LAUNCH',
                'LAUNCH_SUCCESS',
                'LAUNCH_FAILURE',
                'FUNDING',
                'EARNINGS',
                'ACQUISITION',
                'MERGER',
                'PARTNERSHIP',
                'REGULATORY_CHANGE',
                'GOVERNMENT_POLICY',
                'TECHNOLOGY_MILESTONE',
                'CAPACITY_EXPANSION',
                'LEADERSHIP_CHANGE',
                'LEGAL_OR_COMPLIANCE',
                'OTHER',
                'NO_EVENT'
            )
        ),
    constraint article_analyses_impact_direction_check
        check (
            impact_direction is null
            or impact_direction in (
                'POSITIVE',
                'NEGATIVE',
                'NEUTRAL',
                'MIXED',
                'UNCERTAIN'
            )
        ),
    constraint article_analyses_impact_strength_check
        check (impact_strength is null or impact_strength between 1 and 5),
    constraint article_analyses_importance_score_check
        check (importance_score is null or importance_score between 0 and 100),
    constraint article_analyses_confidence_check
        check (confidence is null or confidence between 0 and 1),
    constraint article_analyses_time_horizon_check
        check (
            time_horizon is null
            or time_horizon in (
                'IMMEDIATE',
                'SHORT_TERM',
                'MEDIUM_TERM',
                'LONG_TERM',
                'UNCERTAIN'
            )
        ),
    constraint article_analyses_input_type_check
        check (input_type in ('RSS_SUMMARY', 'ARTICLE_BODY')),
    constraint article_analyses_success_fields_check
        check (
            status <> 'SUCCESS'
            or (
                has_event is not null
                and event_type is not null
                and importance_score is not null
                and confidence is not null
                and time_horizon is not null
                and summary is not null
                and btrim(summary) <> ''
                and analyzed_at is not null
                and error_message is null
            )
        ),
    constraint article_analyses_event_consistency_check
        check (
            status <> 'SUCCESS'
            or (
                (
                    has_event = true
                    and event_type <> 'NO_EVENT'
                    and impact_direction is not null
                    and impact_strength is not null
                )
                or (
                    has_event = false
                    and event_type = 'NO_EVENT'
                    and impact_direction is null
                    and impact_strength is null
                    and event_date is null
                )
            )
        ),
    constraint article_analyses_failure_error_check
        check (status <> 'FAILED' or error_message is not null),
    constraint article_analyses_article_version_unique
        unique (article_id, analysis_version)
);

-- Normalized links preserve referential integrity. Company/topic names can be
-- obtained through joins instead of being copied into every analysis row.
create table if not exists public.article_analysis_companies (
    analysis_id bigint not null references public.article_analyses(analysis_id)
        on delete cascade,
    company_id bigint not null references public.companies(company_id)
        on delete cascade,
    company_role text not null default 'AFFECTED',
    primary key (analysis_id, company_id),
    constraint article_analysis_companies_role_check
        check (company_role in ('AFFECTED', 'MENTIONED'))
);

create table if not exists public.article_analysis_topics (
    analysis_id bigint not null references public.article_analyses(analysis_id)
        on delete cascade,
    topic_id bigint not null references public.industry_topics(topic_id)
        on delete cascade,
    primary key (analysis_id, topic_id)
);

create index if not exists article_analyses_article_idx
    on public.article_analyses (article_id);

create index if not exists article_analyses_status_idx
    on public.article_analyses (status, started_at);

create index if not exists article_analyses_event_type_idx
    on public.article_analyses (event_type)
    where status = 'SUCCESS' and has_event = true;

create index if not exists article_analyses_importance_idx
    on public.article_analyses (importance_score desc)
    where status = 'SUCCESS';

create index if not exists article_analysis_companies_company_idx
    on public.article_analysis_companies (company_id, analysis_id);

create index if not exists article_analysis_topics_topic_idx
    on public.article_analysis_topics (topic_id, analysis_id);

comment on table public.article_analyses is
    'Versioned structured LLM analysis of one article; not a canonical event.';
comment on column public.article_analyses.analysis_version is
    'Application analysis version used for repeat prevention and reprocessing.';
comment on column public.article_analyses.prompt_version is
    'Version of the analyzer prompt that produced the result.';
comment on column public.article_analyses.input_type is
    'Whether analysis used an RSS summary or an extracted article body.';

commit;
