-- Canonical Event Clustering Stage 1: canonical events, evidence links, and
-- versioned clustering audit state.
--
-- article_analyses remains the per-article evidence layer. A canonical event
-- represents one real-world occurrence that may be supported by many analyses.

begin;

create table if not exists public.events (
    event_id bigint generated by default as identity primary key,
    status text not null default 'ACTIVE',
    canonical_title text not null,
    event_type text not null,
    impact_direction text not null,
    impact_strength smallint not null,
    importance_score smallint not null,
    confidence numeric(4, 3) not null,
    time_horizon text not null,
    event_date date,
    canonical_summary text not null,
    industry_implication text,
    facts text[] not null default '{}'::text[],
    risk_factors text[] not null default '{}'::text[],
    first_published_at timestamp with time zone,
    last_published_at timestamp with time zone,
    created_from_analysis_id bigint references public.article_analyses(analysis_id)
        on delete set null,
    merged_into_event_id bigint references public.events(event_id)
        on delete restrict,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint events_status_check
        check (status in ('ACTIVE', 'MERGED', 'REJECTED')),
    constraint events_nonempty_text_check
        check (
            btrim(canonical_title) <> ''
            and btrim(canonical_summary) <> ''
        ),
    constraint events_event_type_check
        check (
            event_type in (
                'GOVERNMENT_CONTRACT',
                'COMMERCIAL_CONTRACT',
                'PRODUCT_LAUNCH',
                'SATELLITE_LAUNCH',
                'LAUNCH_SUCCESS',
                'LAUNCH_FAILURE',
                'FUNDING',
                'EARNINGS',
                'ACQUISITION',
                'MERGER',
                'PARTNERSHIP',
                'REGULATORY_CHANGE',
                'GOVERNMENT_POLICY',
                'TECHNOLOGY_MILESTONE',
                'CAPACITY_EXPANSION',
                'LEADERSHIP_CHANGE',
                'LEGAL_OR_COMPLIANCE',
                'OTHER'
            )
        ),
    constraint events_impact_direction_check
        check (
            impact_direction in (
                'POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', 'UNCERTAIN'
            )
        ),
    constraint events_impact_strength_check
        check (impact_strength between 1 and 5),
    constraint events_importance_score_check
        check (importance_score between 0 and 100),
    constraint events_confidence_check
        check (confidence between 0 and 1),
    constraint events_time_horizon_check
        check (
            time_horizon in (
                'IMMEDIATE', 'SHORT_TERM', 'MEDIUM_TERM',
                'LONG_TERM', 'UNCERTAIN'
            )
        ),
    constraint events_publication_window_check
        check (
            first_published_at is null
            or last_published_at is null
            or first_published_at <= last_published_at
        ),
    constraint events_merge_state_check
        check (
            (status = 'MERGED' and merged_into_event_id is not null)
            or (status <> 'MERGED' and merged_into_event_id is null)
        ),
    constraint events_no_self_merge_check
        check (merged_into_event_id is null or merged_into_event_id <> event_id)
);

create table if not exists public.event_articles (
    event_id bigint not null references public.events(event_id)
        on delete cascade,
    analysis_id bigint not null references public.article_analyses(analysis_id)
        on delete cascade,
    match_method text not null,
    match_score numeric(5, 4),
    match_confidence numeric(4, 3),
    match_reason text,
    linked_at timestamp with time zone not null default now(),
    primary key (event_id, analysis_id),
    constraint event_articles_analysis_unique unique (analysis_id),
    constraint event_articles_match_method_check
        check (match_method in ('NEW_EVENT', 'DETERMINISTIC', 'LLM', 'MANUAL')),
    constraint event_articles_match_score_check
        check (match_score is null or match_score between 0 and 1),
    constraint event_articles_match_confidence_check
        check (match_confidence is null or match_confidence between 0 and 1)
);

create table if not exists public.event_companies (
    event_id bigint not null references public.events(event_id)
        on delete cascade,
    company_id bigint not null references public.companies(company_id)
        on delete cascade,
    company_role text not null default 'AFFECTED',
    primary key (event_id, company_id),
    constraint event_companies_role_check
        check (company_role in ('AFFECTED', 'MENTIONED'))
);

create table if not exists public.event_topics (
    event_id bigint not null references public.events(event_id)
        on delete cascade,
    topic_id bigint not null references public.industry_topics(topic_id)
        on delete cascade,
    primary key (event_id, topic_id)
);

create table if not exists public.event_clustering_runs (
    clustering_run_id bigint generated by default as identity primary key,
    analysis_id bigint not null references public.article_analyses(analysis_id)
        on delete cascade,
    clustering_version text not null,
    status text not null default 'RUNNING',
    decision text,
    decision_method text,
    selected_event_id bigint references public.events(event_id)
        on delete set null,
    candidate_count integer not null default 0,
    best_similarity numeric(5, 4),
    model text,
    prompt_version text,
    decision_reason text,
    error_message text,
    started_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,

    constraint event_clustering_runs_version_unique
        unique (analysis_id, clustering_version),
    constraint event_clustering_runs_status_check
        check (status in ('RUNNING', 'SUCCESS', 'FAILED')),
    constraint event_clustering_runs_decision_check
        check (decision is null or decision in ('NEW_EVENT', 'MATCHED')),
    constraint event_clustering_runs_method_check
        check (
            decision_method is null
            or decision_method in ('DETERMINISTIC', 'LLM', 'MANUAL')
        ),
    constraint event_clustering_runs_candidate_count_check
        check (candidate_count >= 0),
    constraint event_clustering_runs_similarity_check
        check (best_similarity is null or best_similarity between 0 and 1),
    constraint event_clustering_runs_success_check
        check (
            status <> 'SUCCESS'
            or (
                decision is not null
                and decision_method is not null
                and selected_event_id is not null
                and error_message is null
                and completed_at is not null
            )
        ),
    constraint event_clustering_runs_failure_check
        check (status <> 'FAILED' or error_message is not null)
);

create index if not exists events_active_type_date_idx
    on public.events (event_type, event_date desc)
    where status = 'ACTIVE';

create index if not exists events_active_publication_idx
    on public.events (last_published_at desc)
    where status = 'ACTIVE';

create index if not exists event_articles_event_idx
    on public.event_articles (event_id, linked_at);

create index if not exists event_companies_company_idx
    on public.event_companies (company_id, event_id);

create index if not exists event_topics_topic_idx
    on public.event_topics (topic_id, event_id);

create index if not exists event_clustering_runs_status_idx
    on public.event_clustering_runs (status, started_at);

comment on table public.events is
    'Canonical real-world events supported by one or more article analyses.';
comment on table public.event_articles is
    'Evidence links; one article analysis may belong to only one canonical event.';
comment on table public.event_clustering_runs is
    'Versioned audit and repeat-prevention state for event clustering decisions.';
comment on column public.events.created_from_analysis_id is
    'The first analysis used to create the canonical event; not its only evidence.';
comment on column public.event_clustering_runs.clustering_version is
    'Application clustering version used for repeat prevention and reprocessing.';

commit;
