-- Canonical Event Stage 5: auditable consolidation of linked article evidence.

begin;

create table if not exists public.event_updates (
    event_update_id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(event_id)
        on delete cascade,
    triggering_analysis_id bigint references public.article_analyses(analysis_id)
        on delete set null,
    evidence_analysis_ids bigint[] not null,
    evidence_signature text not null,
    update_version text not null,
    status text not null default 'RUNNING',
    action text,
    has_material_update boolean,
    before_state jsonb not null,
    proposed_state jsonb,
    after_state jsonb,
    new_information text[] not null default '{}'::text[],
    contradictions text[] not null default '{}'::text[],
    change_summary text,
    model text not null,
    prompt_version text not null,
    error_message text,
    started_at timestamp with time zone not null default now(),
    completed_at timestamp with time zone,

    constraint event_updates_evidence_nonempty_check
        check (cardinality(evidence_analysis_ids) >= 2),
    constraint event_updates_signature_nonempty_check
        check (btrim(evidence_signature) <> ''),
    constraint event_updates_unique
        unique (event_id, evidence_signature, update_version),
    constraint event_updates_status_check
        check (status in ('RUNNING', 'SUCCESS', 'FAILED')),
    constraint event_updates_action_check
        check (action is null or action in ('UPDATED', 'NO_CHANGE')),
    constraint event_updates_success_check
        check (
            status <> 'SUCCESS'
            or (
                action is not null
                and has_material_update is not null
                and proposed_state is not null
                and after_state is not null
                and error_message is null
                and completed_at is not null
            )
        ),
    constraint event_updates_failure_check
        check (status <> 'FAILED' or error_message is not null)
);

create index if not exists event_updates_event_idx
    on public.event_updates (event_id, started_at desc);

create index if not exists event_updates_status_idx
    on public.event_updates (status, started_at);

comment on table public.event_updates is
    'Audited before/proposed/after states for canonical event consolidation.';
comment on column public.event_updates.evidence_signature is
    'Stable hash of the linked analysis IDs used for repeat prevention.';

commit;
